[package]
name = "ops"
edition = "2018"
version = "0.1.0"
authors = ["Szymon Wieloch <szymon.wieloch@gmail.com>"]

[dependencies]
opslib = { path = "opslib" }
clap = "2.26.0"
log = "0.3.8"
ipnetwork = "0.12.6"
iprange = "0.4.1"
ipnet = "1.0.0"
range-map = "0.1.5"

[workspace]
members = ["opslib"]

#[features]
#ipv6-methods = ["ipnetwork/ipv6-methods"]
